name: Check PR Base Branch Commits

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  get-base-branch-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get the base branch name
        id: vars
        run: echo "::set-output name=BASE_BRANCH::${{ github.event.pull_request.base.ref }}"

      - name: Checkout the base branch
        run: git checkout ${{ steps.vars.outputs.BASE_BRANCH }}

      - name: Fetch all commits on the base branch
        run: git fetch origin ${{ steps.vars.outputs.BASE_BRANCH }}

      - name: Show commit log
        run: git log -10 --oneline
